 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/triviattack-cicd:$COMMIT_SHA', './api/']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/triviattack-frontend:$COMMIT_SHA', './client/triviattack/']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/triviattack-cicd:$COMMIT_SHA']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/triviattack-frontend:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'triviattack-cicd'
   - '--image'
   - 'gcr.io/$PROJECT_ID/triviattack-cicd:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'triviattack-frontend'
   - '--image'
   - 'gcr.io/$PROJECT_ID/triviattack-frontend:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
 images:
 - 'gcr.io/$PROJECT_ID/triviattack-cicd:$COMMIT_SHA'
 - 'gcr.io/$PROJECT_ID/triviattack-frontend:$COMMIT_SHA'