steps:

- id: 'Download dependencies'
  name: golang
  args: ['go', 'mod', 'download']

# Setup resources for system tests
- id: 'Build Container Image'
  name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: pack
  args:
    - build
    - '--builder=gcr.io/buildpacks/builder:v1'
    - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
    

- id: 'Push Container Image'
  name: 'gcr.io/cloud-builders/docker:latest'
  args:
    - push
    - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA' 

- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud:latest'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      gcloud run deploy ${_SERVICE_NAME}-$BUILD_ID \
        --image '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA' \
        --region ${_DEPLOY_REGION} \
        --no-allow-unauthenticated
- id: 'Retrieve Service URL'
  name: 'gcr.io/cloud-builders/gcloud:latest'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      set -e
      source /workspace/common.sh
      echo $(get_url ${BUILD_ID}) > _service_url
      echo $(get_idtoken) > _id_token
  env:
    - '_SERVICE_NAME=${_SERVICE_NAME}'
    - '_DEPLOY_REGION=${_DEPLOY_REGION}'
    - 'BUILD_ID=${BUILD_ID}'
    - 'PROJECT_ID=${PROJECT_ID}'

substitutions:
  _GCR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: triviattack
  _DEPLOY_REGION: us-central1
  _REPOSITORY: samples

options:
  volumes:
  - name: go-modules
    path: /go